Fdem permittivity
simpeg/simpeg pull request #1236
Opened 2023-06-10 20:37 UTC by lheagy

#### Summary

Add the ability to perform forward simulations in the frequency domain with dielectric permittivity. Note that inversions are not yet supported: 
- derivatives are not yet implemented for the system when permittivity is non-zero (e.g. the gradients still all assume that dielectric permittivity = 0) -- this likely isn't a big deal as permittivity would have to be massive to cause a substantive change in the gradient, but this is something we can address in the future
- right now, `permittivity` is not an invertible property (something for the future) 

#### PR Checklist
* [ ] If this is a work in progress PR, set as a Draft PR
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/content/basic/practices.html#style).
* [ ] Added [tests](https://docs.simpeg.xyz/content/basic/practices.html#testing) to verify changes to the code.
* [ ] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/content/basic/practices.html#documentation).
* [ ] Added relevant method tags (i.e. `GRAV`, `EM`, etc.)
* [ ] Marked as ready for review (ff this is was a draft PR), and converted 
      to a Pull Request
* [ ] Tagged ``@simpeg/simpeg-developers`` when ready for review.

#### Reference issue

N/A

#### What does this implement/fix?

This extends the forward simulation capabilities and allows us to simulate complex conductivity / dielectric permittivity

#### Additional information

Note that the naming choice of `permittivity` rather than `epsilon` is different than the convention of naming properties by their greek letters and is in anticipation of the changes we will make with #1227

2023-06-14 22:41 UTC, lheagy commented
Also, if you would like to try this out, there is an example here: https://github.com/lheagy/fdem-dielectric-permittivity

2023-06-27 19:07 UTC, jcapriot requested changes
looks good, just a few small changes.

2023-06-27 19:07 UTC, jcapriot commented on SimPEG/electromagnetics/frequency_domain/fields.py
> +            return self._MeI * self._MeSigma * self._e(bSolution, source_list)
```suggestion
            return self._MeI * (self._MeSigma * self._e(bSolution, source_list))
```
avoid the matrix-matrix multiplication

2023-06-27 19:07 UTC, jcapriot commented on SimPEG/electromagnetics/frequency_domain/simulation.py
> +                "Simulations using permittivity have not yet been thoroughly tested yet, and derivatives are not implemented. Contributions welcome!"
```suggestion
                "Simulations using permittivity have not yet been thoroughly tested, and derivatives are not implemented. Contributions welcome!"
```

2023-06-27 19:07 UTC, jcapriot commented on SimPEG/electromagnetics/frequency_domain/simulation.py
> +@with_property_mass_matrices("permittivity")
```suggestion
```

You should be able to remove this as you are not doing anything like `MePermitivity`

2023-07-05 17:54 UTC, lheagy commented
accepted your changes, thanks Joe!

2023-07-06 16:26 UTC, lheagy commented
Assuming this passes :) it is good to go from my perspective. Feel free to squash and merge. There are a number of small commits for fixing flake and small typos

2023-07-06 18:33 UTC, jcapriot commented
I just tagged a new patch version for geoana, (0.4.1). Once that gets release we can update the version required for SimPEG to that, and it should fix the broken tests here.

2023-07-12 16:55 UTC, merged