Documentation improvents for classes in Objective Function Pieces
simpeg/simpeg pull request #1292
Opened 2023-10-12 00:01 UTC by ghwilliams

@dccowan Please take a look at this tentative improvement of the documentation. 

#### Summary

#### PR Checklist
* [ ] If this is a work in progress PR, set as a Draft PR
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/content/getting_started/contributing/code-style.html).
* [ ] Added [tests](https://docs.simpeg.xyz/content/getting_started/practices.html#testing) to verify changes to the code.
* [ ] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/content/getting_started/practices.html#documentation).
* [ ] Marked as ready for review (if this is was a draft PR), and converted 
      to a Pull Request
* [ ] Tagged ``@simpeg/simpeg-developers`` when ready for review.

#### Reference issue

#### What does this implement/fix?

#### Additional information

2023-10-14 11:56 UTC, ghwilliams commented
I've just noticed that I missed some corrections, doing it right now.

2023-10-16 23:12 UTC, ghwilliams commented
I've finished what I think was necessary for this PR to be ready for a review.

2023-11-28 18:31 UTC, dccowan commented
@ghwilliams please add summary and keep PR checklist up to date. Suggest:

**Summary:** Add proper docstrings for data_misfit.py and objective_function.py (and simulation.py?)

2023-11-28 18:33 UTC, dccowan commented on docs/conf.py
> +    #    "sphinx_gallery.gen_gallery",
Don't forget to uncomment

2023-11-28 18:48 UTC, dccowan commented on SimPEG/data_misfit.py
>  class BaseDataMisfit(L2ObjectiveFunction):
Base classes are a good place to add descriptive docstring for what the .py file actually has. And we need to define the input parameters.

2023-12-07 19:59 UTC, santisoler requested changes
Huge thanks @ghwilliams! Awesome job adding all these docstrings. Users will greatly appreciate it.

I've added a few minor suggestions, mostly corrections to LaTeX equations and some changes to follow numpydocs style.

Feel free to commit the suggestions, or make your own changes if you think they could be improved. Let me know what do you think.

I'm looking forward to merge this and see you in the contributors list! 🚀

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +        list of int (n_data, n_param)
Just a small correction on the type of the returned object:
```suggestion
        tuple of int (n_data, n_param)
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +        None, SimPEG.utils.Counter
Small change:
```suggestion
        None or SimPEG.utils.Counter
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +        Where :math:`\mathbf{d}_obs` is the observed data vector and :math:`\mathbf{d}_{pred}`
Minor correction in LaTeX equation:
```suggestion
        Where :math:`\mathbf{d}_\text{obs}` is the observed data vector and :math:`\mathbf{d}_\text{pred}`
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +            \mathbf{r} = \mathbf{d}_{pred} - \mathbf{d}_{obs}
```suggestion
            \mathbf{r} = \mathbf{d}_\text{pred} - \mathbf{d}_\text{obs}
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +        f : None, SimPEG.fields.Fields (optional)
Small change to follow [numpydocs style for optional parameters](https://numpydoc.readthedocs.io/en/latest/format.html#parameters)
```suggestion
        f : None or SimPEG.fields.Fields, optional
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +        \big ( \mathbf{d}_{pred} - \mathbf{d}_{obs} \big ) \big \|_2^2
```suggestion
        \big ( \mathbf{d}_\text{pred} - \mathbf{d}_\text{obs} \big ) \big \|_2^2
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +    where :math:`\mathbf{d}_obs` is the observed data vector, :math:`\mathbf{d}_{pred}`
```suggestion
    where :math:`\mathbf{d}_\text{obs}` is the observed data vector, :math:`\mathbf{d}_\text{pred}`
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +        \mathbf{W_d} = diag \left ( \boldsymbol{\varepsilon}^{-1} \right )
Minor change in LaTeX style:
```suggestion
        \mathbf{W_d} = \text{diag} \left ( \boldsymbol{\varepsilon}^{-1} \right )
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +    counter : None, SimPEG.utils.Counter
```suggestion
    counter : None or SimPEG.utils.Counter
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +        v : None, (n_param, ) numpy.ndarray (optional)
```suggestion
        v : None or (n_param, ) numpy.ndarray, optional
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +        (n_param, n_param) scipy.sparse.csr_matrix | (n_param, ) numpy.ndarray
```suggestion
        (n_param, n_param) scipy.sparse.csr_matrix or (n_param, ) numpy.ndarray
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/objective_function.py
> +    counter : None, SimPEG.utils.Counter
```suggestion
    counter : None or SimPEG.utils.Counter
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/data_misfit.py
> +    where :math:`\mathbf{m}` is the model vector, :math:`mathbf{W}` is a linear weighting
Add missing backslash:
```suggestion
    where :math:`\mathbf{m}` is the model vector, :math:`\mathbf{W}` is a linear weighting
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/objective_function.py
> +        v : None, (n_param, ) numpy.ndarray (optional)
```suggestion
        v : None or (n_param, ) numpy.ndarray, optional
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/objective_function.py
> +        (n_param, n_param) scipy.sparse.csr_matrix | (n_param, ) numpy.ndarray
```suggestion
        (n_param, n_param) scipy.sparse.csr_matrix or (n_param, ) numpy.ndarray
```

2023-12-07 19:59 UTC, santisoler commented on SimPEG/objective_function.py
> +        Whether to unpack the multiple objective functions when adding them to
Nice catch!

2023-12-07 19:59 UTC, santisoler commented on SimPEG/objective_function.py
> +        this method returns the multipliers :math:`c_i` in order.
I think this line could be misleading users to think that multipliers are returned in ascending/descending order. I'm adding this suggestion, let me know what do you think.
```suggestion
        This method returns the multipliers :math:`c_i` in the same order of the ``objfcts``.
```

2023-12-07 20:19 UTC, ghwilliams commented
Thanks @santisoler . I'll review everything and talk to @dccowan to see if we can consider it ready to be merged or if it still needs some corrections.

2024-01-02 18:03 UTC, santisoler approved these changes

2024-01-02 18:05 UTC, santisoler commented
Thanks @ghwilliams for applying all the suggestions. I think this is ready to be merged. I've just updated the branch with the latest changes in `main`. We shall wait CI (automated checks and tests) to pass and then we should merge it 🚀 

Thanks again for the contributions! They are greatly appreciated!

2024-01-11 18:08 UTC, santisoler commented
Thanks @ghwilliams for all the effort of writing these docstrings! Your contributions are greatly appreciated!

I'm merging this! :rocket:

2024-01-11 18:09 UTC, merged