Exponential Sinusoids Similation
simpeg/simpeg pull request #1337
Opened 2024-01-24 06:21 UTC by lheagy

### Summary
- define the kernel functions at cell nodes rather than at cell centers 
- also move the __init__ from the middle of the class to the top of the class definition

### Reasoning 
- kernel functions should be defined on nodes as we think of them being piecewise linear (rather than discontinuous as we talk about at cell centers). This makes it more in line with other physical simulations
- this then also introduces the concept of a staggered grid
- both of these things are important for teaching purposes

### Notes
- [ ] there is one test where we manually check the output of the data. This will fail currently. We should decide whether we want to keep this test and update it or simply remove it.

2024-01-24 06:22 UTC, lheagy commented on SimPEG/simulation.py
> +    def __init__(self, n_kernels=20, p=-0.25, q=0.25, j0=0.0, jn=60.0, **kwargs):
the only change here is that I moved the init

2024-01-31 19:42 UTC, jcapriot commented
Would it make sense to instead define an option on the initialization akin to:

```
integrate : {'mid', 'trap', 'exact'}
```

and then just have the kernel functions do the correct thing?

2024-02-11 17:33 UTC, lheagy commented
> Would it make sense to instead define an option on the initialization akin to:
> 
> ```
> quadrature : {'mid', 'trap', None}
>     quadrature rule to apply to the kernel integral, None uses analytic solution.
> ```
> 
> and then just have the kernel functions do the correct thing?

Thanks for this suggestion @jcapriot! In my opinion though, I would be supportive of being opinionated on this example and sticking to one option. There are a couple of reasons for this: (1) defining the kernels on nodes is very much in line with the finite volume approach we take throughout SimPEG, (2) this example is generally the first that we have students work with, so keeping it simple reduces opportunities for confusion. 

For example, when I am teaching this, here are the slides I am using to introduce it 

![image](https://github.com/simpeg/simpeg/assets/6361812/ec6b7051-163d-4835-83e2-7495946a1308)

![image](https://github.com/simpeg/simpeg/assets/6361812/9313d4e2-04aa-474b-b32c-c8e3dd4991cf)

So here, I think less is more.

2024-02-26 00:26 UTC, lheagy commented
Does anyone have concerns about us going ahead with this? I would love to be able to point to it from my class in the next couple of weeks if possible.

2024-02-27 14:55 UTC, lheagy commented
👋 @simpeg/simpeg-admins: if someone has a moment to review this, I would appreciate it! I would love to be able to point to this in the class I am teaching on Thursday.

2024-02-27 15:49 UTC, jcapriot requested changes
Just one small change.

Also, if you want to add a tiny bit to the docstrings saying that it uses Trapezoidal rule to compute the kernel integral, I wouldn’t say no.

2024-02-27 15:49 UTC, jcapriot commented on SimPEG/simulation.py
> +                print(self.g(i).shape)
Looks to be a spurious print statement here

2024-02-28 22:40 UTC, lheagy commented
Good call, many thanks @jcapriot! I removed the print statement and updated the docstring for the class.

2024-02-28 23:21 UTC, jcapriot approved these changes
looks good!

2024-02-29 05:33 UTC, merged