Add release notes for SimPEG v0.21
simpeg/simpeg pull request #1409
Opened 2024-04-08 21:44 UTC by santisoler

#### Summary

Add release notes for SimPEG v0.21.0 to the docs.

#### PR Checklist
* [ ] If this is a work in progress PR, set as a Draft PR
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/content/getting_started/contributing/code-style.html).
* [ ] Added [tests](https://docs.simpeg.xyz/content/getting_started/practices.html#testing) to verify changes to the code.
* [ ] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/content/getting_started/practices.html#documentation).
* [ ] Marked as ready for review (if this is was a draft PR), and converted 
      to a Pull Request
* [ ] Tagged ``@simpeg/simpeg-developers`` when ready for review.

#### Reference issue

#### What does this implement/fix?

#### Additional information

2024-04-08 21:51 UTC, santisoler commented
@jcapriot @lheagy would you like to take a look at these release notes?

2024-04-08 22:53 UTC, jcapriot requested changes

2024-04-08 22:53 UTC, jcapriot commented on docs/content/release/0.21.0-notes.rst
> +of Choclo and Numba.
```suggestion
of Choclo and Numba.  To make use of this functionality you will need to install `choclo` in addition to `simpeg`.
```

2024-04-08 22:53 UTC, jcapriot commented on docs/content/release/0.21.0-notes.rst
> +direction, enabling anisotropic weighting.
```suggestion
direction, enabling anisotropic weighting. This regularization also works for a `SimplexMesh`.
```

2024-04-08 22:53 UTC, jcapriot commented on docs/content/release/0.21.0-notes.rst
> +sigmoid of the model parameters.
```suggestion
sigmoid of the model parameters. This is an alternative method to incorporate upper and lower bounds on model parameters.
```

2024-04-08 22:53 UTC, jcapriot commented on docs/content/release/0.21.0-notes.rst
> +EM simulations through the ``getJ`` method.
```suggestion
Create Jacobian matrix in NSEM and FDEM simulations
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The frequency domain electromagnetic simulations (including natural source) now support creating and storing the Jacobian matrix. You can access it by using the ``getJ`` method.
```

2024-04-08 22:53 UTC, jcapriot commented on docs/content/release/0.21.0-notes.rst
> +
Consider adding a TOC at the top,

```
.. contents:: Highlights
    :depth: 3
```
or whichever depth makes most sense.

2024-04-08 23:01 UTC, santisoler commented on docs/content/release/0.21.0-notes.rst
> +of Choclo and Numba.
Totally! Nice catch.

2024-04-08 23:09 UTC, santisoler commented on docs/content/release/0.21.0-notes.rst
> +addition to `SimPEG`.
```suggestion
addition to ``SimPEG``.
```

2024-04-09 04:19 UTC, lheagy commented on docs/content/release/0.21.0-notes.rst
> +Updates
I believe that the SP simulation is also new in this release, is that right?

2024-04-09 04:22 UTC, lheagy commented on docs/content/release/0.21.0-notes.rst
> +Updates
Ah, nevermind, it looks like this was in 0.20
https://github.com/simpeg/simpeg/pull/1211

2024-04-09 04:23 UTC, lheagy approved these changes
This looks good to me, thanks for putting it together @santisoler, and for the review @jcapriot! It will be great to get this out into the world 🚀

2024-04-09 16:40 UTC, merged