Simplify interface of UniformBackgroundField
simpeg/simpeg pull request #1421
Opened 2024-04-11 17:07 UTC by santisoler

#### Summary

Remove the `**kwargs` from the constructor of `UniformBackgroundField`. Make `receiver_list`, `amplitude`, `inclination` and `declination` as required arguments without any default value. Include type hints in the signature of the constructor. Add check for type of receivers to the constructor of `UniformBackgroundField`. Add test that checks the value of `UniformBackgroundField.b0`, passing `receiver_list` as an actual list of point receivers and as `None`. Add test that checks if the error is raised after passing invalid receiver type. Minor improvements to the docstring of the class.

#### PR Checklist
* [ ] If this is a work in progress PR, set as a Draft PR
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/content/getting_started/contributing/code-style.html).
* [ ] Added [tests](https://docs.simpeg.xyz/content/getting_started/practices.html#testing) to verify changes to the code.
* [ ] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/content/getting_started/practices.html#documentation).
* [ ] Marked as ready for review (if this is was a draft PR), and converted
      to a Pull Request
* [ ] Tagged ``@simpeg/simpeg-developers`` when ready for review.

#### Reference issue

Fixes #1418

#### What does this implement/fix?

#### Additional information

2024-04-25 19:19 UTC, jcapriot requested changes
I would recommend either overloading the parent's `receiver_list.setter` or just completely overloading the property

If you just want to overload the setter:
```python
    @BaseSrc.receiver_list.setter
    def receiver_list(self, value):
        self._receiver_list = validate_list_of_types(
            "source_list", new_list, Point, ensure_unique=True
        )
```

or if you want to overload the getter and setter (probably to make the `receiver_list` property have a slightly more relevant doctoring).

```python
    @property
    def receiver_list(self):
        """List of receivers associated with the survey

        Returns
        -------
        list of .magnetic.Point
            List of magnetic receivers associated with the survey
        """
        return self._receiver_list

    @receiver_list.setter
    def receiver_list(self, value):
        self._receiver_list = validate_list_of_types(
            "source_list", new_list, Point, ensure_unique=True
        )
```

2024-04-25 19:26 UTC, santisoler commented
Sounds good. I agree that would be better, indeed. One thing that is not very clear in the `validate_list_of_types` is that it doesn't fail if the passed object is not a list, but just a single object of the valid `class_type`. Minor thing, but probably worth documenting.

2024-04-26 22:48 UTC, santisoler commented on tests/utils/test_io_utils.py
> +            receiver_list=[rx1, rx2], amplitude=50_000, inclination=90, declination=0
```suggestion
            receiver_list=[rx, rx2], amplitude=50_000, inclination=90, declination=0
```

2024-04-30 18:55 UTC, jcapriot commented
So the only awkward thing left here is that `receivers_list` was an optional parameter that defaulted to `None` which is a valid thing, (mostly in the context of the PDE solution where you might be interested in the fields themselves but have no receivers). Now it would require explicitly setting `receivers_list=None` to obtain the same behavior.

2024-05-01 15:48 UTC, santisoler commented
True. I think it's a good compromise. An alternative would be to define the receiver list as an optional argument. I don't have strong feelings toward any of these options.

2024-05-01 15:55 UTC, jcapriot commented
> True. I think it's a good compromise. An alternative would be to define the receiver list as an optional argument. I don't have strong feelings toward any of these options.

The thing is, you can't make the `receiver_list` optional without changing the order of the arguments, which is not an option. So the only real options are to either make everything required (which is technically a breaking change), or to just leave them all as keyword arguments. I think the part just removing the `**kwargs` is enough to make it behave better.

2024-05-01 16:47 UTC, santisoler commented
I wouldn't like to change order of arguments, that's why I decided to make `receiver_list` as required from the start.

I also agree with the idea of not setting default values for the background field. Setting them as required arguments force users to consider which values should the pass to define the background field. I think that's a good thing.

I don't quite like setting the values as None and then raising an error after them. I think it'll create some confusion, will require us to add checks and tests for those checks, and is not very clean. Moreover, changing a default value is also a breaking change, so we are not avoiding that either.

That's why I think having `receiver_list` as required is a good compromise: we'll force users to pass the values for the background field, with the side effect of having to pass the receiver list as well.

2024-05-15 05:17 UTC, lheagy approved these changes
Looks good to me!

2024-05-15 18:30 UTC, merged