Update and fix instructions to build the docs
simpeg/simpeg pull request #1583
Opened 2024-11-18 19:50 UTC by santisoler

#### Summary

Update the instructions on how to build the documentation pages and serve them locally.

#### PR Checklist
* [ ] If this is a work in progress PR, set as a Draft PR
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/latest/content/getting_started/contributing/code-style.html).
* [ ] Added [tests](https://docs.simpeg.xyz/latest/content/getting_started/contributing/testing.html) to verify changes to the code.
* [ ] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/latest/content/getting_started/contributing/documentation.html).
* [ ] Marked as ready for review (if this is was a draft PR), and converted
      to a Pull Request
* [ ] Tagged ``@simpeg/simpeg-developers`` when ready for review.

#### Reference issue

#### What does this implement/fix?

#### Additional information

2024-11-18 23:14 UTC, jcapriot requested changes

2024-11-18 23:14 UTC, jcapriot commented on docs/content/getting_started/contributing/documentation.rst
> +look like. First, make sure that you have :ref:`created and activated an
```suggestion
You can build the documentation pages locally to see how the new changes will look. 
First, make sure that you have :ref:`created and activated an
```

2024-11-18 23:14 UTC, jcapriot commented on docs/content/getting_started/contributing/documentation.rst
> +look like. First, make sure that you have :ref:`created and activated an
The original statement just sounded odd to me...

Also your `:ref:` link is broken

2024-11-19 18:27 UTC, santisoler commented
@jcapriot, I see the `:ref:` link working properly. Is it broken on your side?

2024-11-20 17:56 UTC, jcapriot commented
Yeah, it looks good. I think I was initially caught off guard by the length of the link text,

2024-11-20 17:56 UTC, jcapriot approved these changes

2024-11-20 19:54 UTC, merged