Update io_utils.py
simpeg/simpeg pull request #922
Opened 2020-09-10 22:34 UTC by domfournier

Flip sign of ubc gravity file for Cartesian convention

2020-09-10 22:39 UTC, domfournier commented
That should fix issues with the sign flip seen on the Laguna example.

2020-09-10 22:54 UTC, craigmillernz requested changes
How about 
...between Cartesian coordinate system (internal SimPEG format that expects "positive up" gravity signal) and traditional gravity data conventions (positive down).  For example a traditional negative gravity anomaly is described as "positive up" in Cartesian coordinates and hence the sign needs to be flipped for use in SimPEG.

2020-09-25 07:03 UTC, craigmillernz approved these changes

2020-11-02 20:52 UTC, merged

2021-02-02 18:57 UTC, craigmillernz commented
@domfournier @jcapriot can this be closed? along with #920  ?